In [68]:
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from os import listdir
from PIL import Image

### Transform images into dataframe.

In [85]:
def transform_into_df(path,images,width,height):
    images = sorted(images)
    columns = [*range(0,(width* height))].append('Label')
    outdf=pd.DataFrame(columns=)
    for image in images:
        img = Image.open(path+image)
        pixels = np.array(img.getdata())/255
        outdf.loc[image]=pixels
        Label = image[2]
        outdf.loc[image]= [image,Label]
        
                
    return outdf

Train Dataframe

In [86]:
train_df = transform_into_df('Train/',listdir('Train/'),12,12)
print("Train dataset has {} images with {} pixels each.".format(train_df.shape[0],train_df.shape[1]))

ValueError: cannot set a frame with no defined columns

In [71]:
train_df.head(10)

,0,1,2,3,4,5,6,7,8,9,...,134,135,136,137,138,139,140,141,142,143
A1a1.jpg,0.000000,1.000000,0.984314,0.000000,1.000000,0.039216,0.949020,1.000000,0.988235,0.972549,...,0.972549,1.000000,0.941176,0.929412,0.874510,0.015686,1.000000,1.000000,1.000000,0.000000
A1a2.jpg,0.031373,0.976471,0.972549,0.980392,0.972549,1.000000,0.992157,0.949020,0.988235,1.000000,...,1.000000,1.000000,0.984314,0.980392,0.996078,0.964706,0.937255,0.000000,0.023529,0.945098
A1a3.jpg,0.000000,0.062745,0.964706,0.972549,0.011765,1.000000,0.000000,1.000000,0.941176,0.050980,...,0.960784,1.000000,0.890196,1.000000,0.976471,0.929412,0.000000,1.000000,1.000000,0.050980
A1a4.jpg,0.000000,0.000000,0.976471,1.000000,1.000000,0.917647,0.023529,1.000000,0.968627,1.000000,...,0.980392,0.000000,1.000000,0.901961,0.968627,0.866667,0.937255,1.000000,1.000000,0.839216
A1a5.jpg,1.000000,0.078431,0.000000,0.964706,1.000000,0.972549,0.972549,0.960784,0.992157,0.996078,...,0.972549,0.003922,0.933333,1.000000,0.925490,0.988235,1.000000,0.996078,0.000000,1.000000
A1a6.jpg,0.000000,0.031373,0.968627,0.972549,1.000000,0.960784,0.000000,0.992157,0.984314,0.074510,...,1.000000,0.980392,0.901961,1.000000,0.929412,0.945098,0.992157,1.000000,0.996078,1.000000
A1a7.jpg,0.000000,0.003922,0.972549,0.984314,1.000000,1.000000,0.000000,1.000000,0.972549,1.000000,...,1.000000,0.941176,1.000000,0.917647,0.941176,0.000000,1.000000,1.000000,0.000000,0.933333
A1b1.jpg,1.000000,0.737255,1.000000,0.929412,0.988235,1.000000,0.011765,0.000000,0.000000,0.050980,...,0.964706,0.945098,1.000000,0.964706,0.690196,0.000000,0.980392,0.933333,0.019608,0.011765
A1b2.jpg,0.713725,1.000000,0.964706,0.011765,1.000000,0.117647,0.047059,0.027451,0.000000,1.000000,...,0.905882,1.000000,1.000000,0.000000,0.749020,1.000000,0.952941,0.000000,0.117647,0.000000
A1b3.jpg,0.717647,1.000000,0.949020,0.980392,0.996078,0.113725,0.000000,0.043137,0.000000,0.109804,...,0.972549,1.000000,0.952941,1.000000,0.682353,0.976471,0.941176,0.000000,0.152941,0.000000

Test DataFrame

In [72]:
test_df = transform_into_df('Test/',listdir('Test/'),12,12)
print("Test dataset has {} images with {} pixels each.".format(test_df.shape[0],test_df.shape[1]))

Test dataset has 52 images with 144 pixels each.

In [73]:
test_df.head()

,0,1,2,3,4,5,6,7,8,9,...,134,135,136,137,138,139,140,141,142,143
A1a8.jpg,0.000000,0.121569,0.000000,0.980392,0.972549,0.015686,0.968627,0.945098,1.000000,0.992157,...,1.000000,0.050980,0.0,0.003922,1.000000,0.980392,0.984314,1.000000,0.941176,1.000000
A1a9.jpg,0.000000,0.172549,0.984314,0.913725,1.000000,0.921569,1.000000,0.917647,1.000000,0.000000,...,0.011765,0.968627,1.0,0.898039,0.937255,0.070588,1.000000,0.882353,1.000000,1.000000
A1b8.jpg,1.000000,0.909804,0.988235,0.027451,0.580392,0.000000,0.019608,0.000000,0.000000,0.062745,...,1.000000,0.937255,1.0,1.000000,0.862745,0.003922,0.976471,0.090196,0.937255,0.015686
A1b9.jpg,0.698039,0.780392,0.972549,0.980392,1.000000,0.094118,0.000000,0.007843,0.011765,0.000000,...,0.996078,1.000000,1.0,0.000000,0.678431,0.960784,1.000000,1.000000,0.592157,1.000000
A1c8.jpg,0.039216,0.000000,1.000000,0.768627,0.984314,0.917647,0.992157,1.000000,1.000000,0.000000,...,0.035294,1.000000,1.0,0.992157,0.866667,1.000000,0.000000,1.000000,0.000000,0.007843

### Extract labels.

In [74]:
def create_labels(paths,images):
    counter = 0
    outdf = pd.DataFrame(columns = ['ImageId','Label'])
    images = sorted(images)
    for image in images:
        Label = image[2]
        outdf.loc[counter]= [image,Label]
        counter+=1
                
    return outdf

In [75]:
train_labels = create_labels('Train/',listdir('Train/'))
train_df['Label'] =pd.Series(train_labels['Label'])
train_df.head()

,0,1,2,3,4,5,6,7,8,9,...,135,136,137,138,139,140,141,142,143,Label
A1a1.jpg,0.000000,1.000000,0.984314,0.000000,1.000000,0.039216,0.949020,1.000000,0.988235,0.972549,...,1.000000,0.941176,0.929412,0.874510,0.015686,1.000000,1.000000,1.000000,0.000000,NaN
A1a2.jpg,0.031373,0.976471,0.972549,0.980392,0.972549,1.000000,0.992157,0.949020,0.988235,1.000000,...,1.000000,0.984314,0.980392,0.996078,0.964706,0.937255,0.000000,0.023529,0.945098,NaN
A1a3.jpg,0.000000,0.062745,0.964706,0.972549,0.011765,1.000000,0.000000,1.000000,0.941176,0.050980,...,1.000000,0.890196,1.000000,0.976471,0.929412,0.000000,1.000000,1.000000,0.050980,NaN
A1a4.jpg,0.000000,0.000000,0.976471,1.000000,1.000000,0.917647,0.023529,1.000000,0.968627,1.000000,...,0.000000,1.000000,0.901961,0.968627,0.866667,0.937255,1.000000,1.000000,0.839216,NaN
A1a5.jpg,1.000000,0.078431,0.000000,0.964706,1.000000,0.972549,0.972549,0.960784,0.992157,0.996078,...,0.003922,0.933333,1.000000,0.925490,0.988235,1.000000,0.996078,0.000000,1.000000,NaN